In [296]:
import cplex
from cplex.exceptions import CplexError
import sys
import pandas as pd
import numpy as np
import docplex

In [297]:
def pprint(constraints: list, names: list):
    for c in constraints:
        _c = [(("-"if _i == -1 else "" if _i == 1 else (str(_i if isinstance(_i, int) else round(_i,1)))) + n) for _i, n in zip(c[0], names) if _i != 0]
        print(c[3] + ": ([" + " ".join(_c) + "]  " + c[1] + "  " + str(c[2] if isinstance(c[2], int) else round(c[2],1)) + ")") 

In [298]:
xls = pd.ExcelFile('logistic.xlsx')

vehicles = ["1","2","3","4","5"]                        # V
customers = ["1","2","3","4","5","6","7","8","9"]       # C

num_vehicles = 5
num_customers = 6
locations = ["O"] + customers[:num_customers] + ["X"]   # C': gồm các customers và Depot suất phát + Depot kết thúc

# quy ước: 
#    + (i,j) là cạnh (edge) thuộc tập E
#    + i,j là 2 customer liền kề trên 1 route


In [299]:
my_names = ["x"+str(i)+str(j) + str(k) for k in vehicles[:num_vehicles] for i in (["O"] + customers[:num_customers]) for j in (customers[:num_customers] + ["X"])]
num_names = len(my_names)
print(num_names)
print("Names ", my_names)
def display(constraints):
    pprint(constraints, my_names)

245
Names  ['xO11', 'xO21', 'xO31', 'xO41', 'xO51', 'xO61', 'xOX1', 'x111', 'x121', 'x131', 'x141', 'x151', 'x161', 'x1X1', 'x211', 'x221', 'x231', 'x241', 'x251', 'x261', 'x2X1', 'x311', 'x321', 'x331', 'x341', 'x351', 'x361', 'x3X1', 'x411', 'x421', 'x431', 'x441', 'x451', 'x461', 'x4X1', 'x511', 'x521', 'x531', 'x541', 'x551', 'x561', 'x5X1', 'x611', 'x621', 'x631', 'x641', 'x651', 'x661', 'x6X1', 'xO12', 'xO22', 'xO32', 'xO42', 'xO52', 'xO62', 'xOX2', 'x112', 'x122', 'x132', 'x142', 'x152', 'x162', 'x1X2', 'x212', 'x222', 'x232', 'x242', 'x252', 'x262', 'x2X2', 'x312', 'x322', 'x332', 'x342', 'x352', 'x362', 'x3X2', 'x412', 'x422', 'x432', 'x442', 'x452', 'x462', 'x4X2', 'x512', 'x522', 'x532', 'x542', 'x552', 'x562', 'x5X2', 'x612', 'x622', 'x632', 'x642', 'x652', 'x662', 'x6X2', 'xO13', 'xO23', 'xO33', 'xO43', 'xO53', 'xO63', 'xOX3', 'x113', 'x123', 'x133', 'x143', 'x153', 'x163', 'x1X3', 'x213', 'x223', 'x233', 'x243', 'x253', 'x263', 'x2X3', 'x313', 'x323', 'x333', 'x343', 'x35

In [300]:
cost_matrix = pd.read_excel(xls, 'Cost Matrix')
__v = lambda n: 0 if n == "O" or n == "X" else int(n)
my_obj = [int(cost_matrix.iat[__v(n[1]),__v(n[2]) + 1]) for n in my_names]

print("Object ", my_obj)

Object  [18, 30, 28, 27, 8, 18, 0, 0, 23, 10, 4, 18, 22, 18, 23, 0, 32, 29, 18, 10, 30, 10, 32, 0, 2, 20, 31, 28, 4, 29, 2, 0, 19, 28, 27, 18, 18, 20, 19, 0, 5, 8, 22, 10, 31, 28, 5, 0, 18, 18, 30, 28, 27, 8, 18, 0, 0, 23, 10, 4, 18, 22, 18, 23, 0, 32, 29, 18, 10, 30, 10, 32, 0, 2, 20, 31, 28, 4, 29, 2, 0, 19, 28, 27, 18, 18, 20, 19, 0, 5, 8, 22, 10, 31, 28, 5, 0, 18, 18, 30, 28, 27, 8, 18, 0, 0, 23, 10, 4, 18, 22, 18, 23, 0, 32, 29, 18, 10, 30, 10, 32, 0, 2, 20, 31, 28, 4, 29, 2, 0, 19, 28, 27, 18, 18, 20, 19, 0, 5, 8, 22, 10, 31, 28, 5, 0, 18, 18, 30, 28, 27, 8, 18, 0, 0, 23, 10, 4, 18, 22, 18, 23, 0, 32, 29, 18, 10, 30, 10, 32, 0, 2, 20, 31, 28, 4, 29, 2, 0, 19, 28, 27, 18, 18, 20, 19, 0, 5, 8, 22, 10, 31, 28, 5, 0, 18, 18, 30, 28, 27, 8, 18, 0, 0, 23, 10, 4, 18, 22, 18, 23, 0, 32, 29, 18, 10, 30, 10, 32, 0, 2, 20, 31, 28, 4, 29, 2, 0, 19, 28, 27, 18, 18, 20, 19, 0, 5, 8, 22, 10, 31, 28, 5, 0, 18]


In [301]:
capacity_matrix   = pd.read_excel(xls, 'Capicity')
vehicles_capacity = [capacity_matrix.iat[i,1] for i in range(0, num_vehicles)]
vehicles_capacity

[100, 70, 145, 90, 50]

In [302]:
demand_matrix = pd.read_excel(xls, 'Demand Matrix')
demand = {customers[i]: demand_matrix.iat[i,1] for i in range(0, num_customers)}
demand

{'1': 32, '2': 45, '3': 16, '4': 15, '5': 22, '6': 50}

In [303]:
lower_bounds = [0]*num_names
upper_bounds = [1]*num_names

print("Lb ", lower_bounds)
print("Rb ", upper_bounds)

Lb  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Rb  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [304]:
# CONSTRAINTS_2: 
# # Một cạnh bất kỳ (i->j) chỉ tổn tại trên duy nhất 1 Vehicle. Nhưng i CHỈ LÀ customers, j là locations
constraint_2 = []
_i = 0
for i in customers[:num_customers]:
    con_ = [(1 if name[1] != name[2]  and name[1] == i else 0) for name in my_names]
    if len([c for c in con_  if c != 0]) > 0:
        _i += 1
        constraint_2.append((con_,"E", 1, "C2" + str(_i)))
    
display(constraint_2)


C21: ([x121 x131 x141 x151 x161 x1X1 x122 x132 x142 x152 x162 x1X2 x123 x133 x143 x153 x163 x1X3 x124 x134 x144 x154 x164 x1X4 x125 x135 x145 x155 x165 x1X5]  E  1)
C22: ([x211 x231 x241 x251 x261 x2X1 x212 x232 x242 x252 x262 x2X2 x213 x233 x243 x253 x263 x2X3 x214 x234 x244 x254 x264 x2X4 x215 x235 x245 x255 x265 x2X5]  E  1)
C23: ([x311 x321 x341 x351 x361 x3X1 x312 x322 x342 x352 x362 x3X2 x313 x323 x343 x353 x363 x3X3 x314 x324 x344 x354 x364 x3X4 x315 x325 x345 x355 x365 x3X5]  E  1)
C24: ([x411 x421 x431 x451 x461 x4X1 x412 x422 x432 x452 x462 x4X2 x413 x423 x433 x453 x463 x4X3 x414 x424 x434 x454 x464 x4X4 x415 x425 x435 x455 x465 x4X5]  E  1)
C25: ([x511 x521 x531 x541 x561 x5X1 x512 x522 x532 x542 x562 x5X2 x513 x523 x533 x543 x563 x5X3 x514 x524 x534 x544 x564 x5X4 x515 x525 x535 x545 x565 x5X5]  E  1)
C26: ([x611 x621 x631 x641 x651 x6X1 x612 x622 x632 x642 x652 x6X2 x613 x623 x633 x643 x653 x6X3 x614 x624 x634 x644 x654 x6X4 x615 x625 x635 x645 x655 x6X5]  E  1)


In [305]:
# CONSTRAINTS_3: 
# # Lượng hàng chở đển Customer của 1 Vehicle phải nhỏ hơn bằng Capacity. Nhưng i CHỈ LÀ customers, j là locations
constraint_3 = []
val = lambda v, c, n1, n2, n3: 0 if n3 != v else -1*int(demand[n1]) if n1 != "O" and n1 != n2 else c if n1 == "O" and n2 != "O" else 0
# val = lambda v, c, n1, n2, n3: 0 if n3 != v else int(demand[n1]) if n1 != "O" and n1 != n2 else 0
_i = 0
for veh, cap in zip(vehicles[0:num_vehicles],vehicles_capacity[0:num_vehicles]): 
    _i += 1
    constraint_3.append(([val(veh, float(cap), name[1], name[2], name[3]) for name in my_names],"G", 0, "C3" + str(_i)))


display(constraint_3)

C31: ([100.0xO11 100.0xO21 100.0xO31 100.0xO41 100.0xO51 100.0xO61 100.0xOX1 -32x121 -32x131 -32x141 -32x151 -32x161 -32x1X1 -45x211 -45x231 -45x241 -45x251 -45x261 -45x2X1 -16x311 -16x321 -16x341 -16x351 -16x361 -16x3X1 -15x411 -15x421 -15x431 -15x451 -15x461 -15x4X1 -22x511 -22x521 -22x531 -22x541 -22x561 -22x5X1 -50x611 -50x621 -50x631 -50x641 -50x651 -50x6X1]  G  0)
C32: ([70.0xO12 70.0xO22 70.0xO32 70.0xO42 70.0xO52 70.0xO62 70.0xOX2 -32x122 -32x132 -32x142 -32x152 -32x162 -32x1X2 -45x212 -45x232 -45x242 -45x252 -45x262 -45x2X2 -16x312 -16x322 -16x342 -16x352 -16x362 -16x3X2 -15x412 -15x422 -15x432 -15x452 -15x462 -15x4X2 -22x512 -22x522 -22x532 -22x542 -22x562 -22x5X2 -50x612 -50x622 -50x632 -50x642 -50x652 -50x6X2]  G  0)
C33: ([145.0xO13 145.0xO23 145.0xO33 145.0xO43 145.0xO53 145.0xO63 145.0xOX3 -32x123 -32x133 -32x143 -32x153 -32x163 -32x1X3 -45x213 -45x233 -45x243 -45x253 -45x263 -45x2X3 -16x313 -16x323 -16x343 -16x353 -16x363 -16x3X3 -15x413 -15x423 -15x433 -15x453 -15x463 

In [306]:
# CONSTRAINTS_4: 
# # Với mỗi Vehicle, khi suất phát từ Depot, nó chỉ có thể đến duy nhất 1 Customer
constraint_4 = []
_i = 0
for k in vehicles[0:num_vehicles]:
    _i += 1
    constraint_4.append(([(1 if (name[1] == "O" and name[3] == k) else 0) for name in my_names],"E", 1, "C4" + str(_i)))
    
display(constraint_4)

C41: ([xO11 xO21 xO31 xO41 xO51 xO61 xOX1]  E  1)
C42: ([xO12 xO22 xO32 xO42 xO52 xO62 xOX2]  E  1)
C43: ([xO13 xO23 xO33 xO43 xO53 xO63 xOX3]  E  1)
C44: ([xO14 xO24 xO34 xO44 xO54 xO64 xOX4]  E  1)
C45: ([xO15 xO25 xO35 xO45 xO55 xO65 xOX5]  E  1)


In [307]:
# CONSTRAINTS_5: 
# # Trên route của Vehicle k có cạnh (i->j) : tổng tất cả cạnh đầu 'ra' của i BẰNG tổng tất cả cạnh đầu 'vào' của j
constraint_5 = []
_i = 0
for k in vehicles[0:num_vehicles]:
    for p in customers[:num_customers]: # i
        _i += 1
        foo = lambda k,p,n: 0 if n[3] != k or n[2] == n[1] else 1 if n[1] == p else -1 if n[2] == p else 0                
        constraint_5.append(([foo(k, p, name) for name in my_names],"E", 0, "C5" + str(_i)))

display(constraint_5) 

C51: ([-xO11 x121 x131 x141 x151 x161 x1X1 -x211 -x311 -x411 -x511 -x611]  E  0)
C52: ([-xO21 -x121 x211 x231 x241 x251 x261 x2X1 -x321 -x421 -x521 -x621]  E  0)
C53: ([-xO31 -x131 -x231 x311 x321 x341 x351 x361 x3X1 -x431 -x531 -x631]  E  0)
C54: ([-xO41 -x141 -x241 -x341 x411 x421 x431 x451 x461 x4X1 -x541 -x641]  E  0)
C55: ([-xO51 -x151 -x251 -x351 -x451 x511 x521 x531 x541 x561 x5X1 -x651]  E  0)
C56: ([-xO61 -x161 -x261 -x361 -x461 -x561 x611 x621 x631 x641 x651 x6X1]  E  0)
C57: ([-xO12 x122 x132 x142 x152 x162 x1X2 -x212 -x312 -x412 -x512 -x612]  E  0)
C58: ([-xO22 -x122 x212 x232 x242 x252 x262 x2X2 -x322 -x422 -x522 -x622]  E  0)
C59: ([-xO32 -x132 -x232 x312 x322 x342 x352 x362 x3X2 -x432 -x532 -x632]  E  0)
C510: ([-xO42 -x142 -x242 -x342 x412 x422 x432 x452 x462 x4X2 -x542 -x642]  E  0)
C511: ([-xO52 -x152 -x252 -x352 -x452 x512 x522 x532 x542 x562 x5X2 -x652]  E  0)
C512: ([-xO62 -x162 -x262 -x362 -x462 -x562 x612 x622 x632 x642 x652 x6X2]  E  0)
C513: ([-xO13 x123 x133 x

In [308]:
# CONSTRAINTS_6: 
# # Route của Vehicle k phải luôn trở về Depot (n+1), tức là luôn tồn tại điểm i trên route của k sao cho nó đi đến n+1
# # trong đó n+1 là Depot kết thúc
constraint_6 = []
_i = 0
for veh in vehicles[0:num_vehicles]: 
    _i += 1
    constraint_6.append(([(1 if (name[3] == veh and name[2] == "X") else 0) for name in my_names],"E", 1, "C6" + str(_i)))
    
display(constraint_6)


C61: ([xOX1 x1X1 x2X1 x3X1 x4X1 x5X1 x6X1]  E  1)
C62: ([xOX2 x1X2 x2X2 x3X2 x4X2 x5X2 x6X2]  E  1)
C63: ([xOX3 x1X3 x2X3 x3X3 x4X3 x5X3 x6X3]  E  1)
C64: ([xOX4 x1X4 x2X4 x3X4 x4X4 x5X4 x6X4]  E  1)
C65: ([xOX5 x1X5 x2X5 x3X5 x4X5 x5X5 x6X5]  E  1)


In [309]:
# CONSTRAINTS_X: vehicles ko đc đứng tại chỗ
constraint_x = []
_i = 0

_i += 1
constraint_x.append(([(1 if name[1] == name[2] else 0) for name in my_names],"E", 0, "CX" + str(_i)))

display(constraint_x)


CX1: ([x111 x221 x331 x441 x551 x661 x112 x222 x332 x442 x552 x662 x113 x223 x333 x443 x553 x663 x114 x224 x334 x444 x554 x664 x115 x225 x335 x445 x555 x665]  E  0)


In [310]:
# CONSTRAINTS_Y: vehicles ko đc quay ngược lại
constraint_y = []
_i = 0

for i in customers[:num_customers]:
    for j in customers[:num_customers]:
        if i != j:
            _i += 1
            constraint_y.append(([(1 if ((name[1] == i and j == name[2]) or (name[1] == j and i == name[2])) else 0) for name in my_names],"L", 1, "CX" + str(_i)))

display(constraint_y)


CX1: ([x121 x211 x122 x212 x123 x213 x124 x214 x125 x215]  L  1)
CX2: ([x131 x311 x132 x312 x133 x313 x134 x314 x135 x315]  L  1)
CX3: ([x141 x411 x142 x412 x143 x413 x144 x414 x145 x415]  L  1)
CX4: ([x151 x511 x152 x512 x153 x513 x154 x514 x155 x515]  L  1)
CX5: ([x161 x611 x162 x612 x163 x613 x164 x614 x165 x615]  L  1)
CX6: ([x121 x211 x122 x212 x123 x213 x124 x214 x125 x215]  L  1)
CX7: ([x231 x321 x232 x322 x233 x323 x234 x324 x235 x325]  L  1)
CX8: ([x241 x421 x242 x422 x243 x423 x244 x424 x245 x425]  L  1)
CX9: ([x251 x521 x252 x522 x253 x523 x254 x524 x255 x525]  L  1)
CX10: ([x261 x621 x262 x622 x263 x623 x264 x624 x265 x625]  L  1)
CX11: ([x131 x311 x132 x312 x133 x313 x134 x314 x135 x315]  L  1)
CX12: ([x231 x321 x232 x322 x233 x323 x234 x324 x235 x325]  L  1)
CX13: ([x341 x431 x342 x432 x343 x433 x344 x434 x345 x435]  L  1)
CX14: ([x351 x531 x352 x532 x353 x533 x354 x534 x355 x535]  L  1)
CX15: ([x361 x631 x362 x632 x363 x633 x364 x634 x365 x635]  L  1)
CX16: ([x141 x411 x

In [311]:
def foo(n : int, a : list, o : list):
    temp = {}
    tempa = []
    for ai in a:
        _i =  np.prod([ord(c) + 99 for c in ai])
        if _i not in temp:            
            temp[_i] = ai
            tempa.append(ai)
            
    a = tempa
    arr = []
    if n > 1:
        for ai in a:
            for oi in o:
                if oi not in ai:
                    arr.append(ai + oi)
        return foo(n-1, arr, o)
    else:
        return a

def get_path(n: int, a: list) -> list:
    return foo(n,a,a)


In [312]:
# CONSTRAINT_Z
constraint_z = []
_i = 0

for r in range(3,num_customers + 1): 
    for p in get_path(r, customers[:num_customers]):
        # p = "134"
        # r = 3
        _i += 1
        constraint_z.append(([1 if name[1] in p and name[2] in p and name[1] != name[2] else 0 for name in my_names], "L", r-1, "CZ" + str(_i)))

display(constraint_z)

CZ1: ([x121 x131 x211 x231 x311 x321 x122 x132 x212 x232 x312 x322 x123 x133 x213 x233 x313 x323 x124 x134 x214 x234 x314 x324 x125 x135 x215 x235 x315 x325]  L  2)
CZ2: ([x121 x141 x211 x241 x411 x421 x122 x142 x212 x242 x412 x422 x123 x143 x213 x243 x413 x423 x124 x144 x214 x244 x414 x424 x125 x145 x215 x245 x415 x425]  L  2)
CZ3: ([x121 x151 x211 x251 x511 x521 x122 x152 x212 x252 x512 x522 x123 x153 x213 x253 x513 x523 x124 x154 x214 x254 x514 x524 x125 x155 x215 x255 x515 x525]  L  2)
CZ4: ([x121 x161 x211 x261 x611 x621 x122 x162 x212 x262 x612 x622 x123 x163 x213 x263 x613 x623 x124 x164 x214 x264 x614 x624 x125 x165 x215 x265 x615 x625]  L  2)
CZ5: ([x131 x141 x311 x341 x411 x431 x132 x142 x312 x342 x412 x432 x133 x143 x313 x343 x413 x433 x134 x144 x314 x344 x414 x434 x135 x145 x315 x345 x415 x435]  L  2)
CZ6: ([x131 x151 x311 x351 x511 x531 x132 x152 x312 x352 x512 x532 x133 x153 x313 x353 x513 x533 x134 x154 x314 x354 x514 x534 x135 x155 x315 x355 x515 x535]  L  2)
CZ7: ([x13

In [313]:
# TIME
time_names = ["s"+str(i) + str(k) for i in (["O"] + customers[:num_customers] + ["X"]) for k in vehicles[:num_vehicles]]
full_names = my_names + time_names
print(time_names)
def displayt(constraints):
    pprint(constraints, time_names)

def displayful(constraints):
    pprint(constraints, full_names)

['sO1', 'sO2', 'sO3', 'sO4', 'sO5', 's11', 's12', 's13', 's14', 's15', 's21', 's22', 's23', 's24', 's25', 's31', 's32', 's33', 's34', 's35', 's41', 's42', 's43', 's44', 's45', 's51', 's52', 's53', 's54', 's55', 's61', 's62', 's63', 's64', 's65', 'sX1', 'sX2', 'sX3', 'sX4', 'sX5']


In [314]:
# constraints time 1 s0k = 0 ủa cho thành tổng tất cả là 0 dc ko 
constraints_time_1 = []
constraints_time_1.append(([1 if name[0] == "s" and name[1] == "O" else 0 for name in full_names], "E", 0 , "CT1" ))
    
displayful(constraints_time_1)


CT1: ([sO1 sO2 sO3 sO4 sO5]  E  0)


In [315]:
# Time window 
start_time = pd.read_excel(xls, 'Time Window')['Time Start']
start_time= {loc: float(start_time.iat[i]) for i, loc in zip(range(0,num_customers + 1), ["O"] + customers[:num_customers])}

end_time = pd.read_excel(xls, 'Time Window')['Time End']
end_time = {loc: float(end_time.iat[i]) for i, loc in zip(range(0,num_customers + 1), ["O"] + customers[:num_customers])} 

print(start_time)
print(end_time)


{'O': 0.0, '1': 2.0, '2': 0.0, '3': 3.5, '4': 0.0, '5': 0.0, '6': 0.0}
{'O': 5.0, '1': 13.0, '2': 15.0, '3': 17.0, '4': 11.5, '5': 15.0, '6': 7.0}


In [316]:
# Time matrix
time_matrix = pd.read_excel(xls, 'Time Matrix')

timesdf = time_matrix.iloc[0:num_customers + 2,1:num_customers + 2].values

times = {}
for _i, i in enumerate(["O"] + customers[:num_customers]):
    for _j, j in enumerate(["O"] + customers[:num_customers]):
        key = i+j
        val = timesdf[_i][_j]
        if not key in times:
            times[key]=val
print(timesdf)    
times

[[0.  1.2 1.8 1.6 1.4 0.5 1.1]
 [1.2 0.  1.5 0.8 0.5 1.3 1.7]
 [1.8 1.5 0.  2.1 1.9 1.1 0.6]
 [1.6 0.8 2.1 0.  0.2 0.7 1.8]
 [1.4 0.5 1.9 0.1 0.  1.1 1.7]
 [0.5 1.3 1.1 0.7 1.1 0.  0.3]
 [1.1 1.7 0.6 2.  1.7 0.3 0. ]
 [0.3 1.3 1.7 1.3 0.8 0.8 1.2]]


{'OO': 0.0,
 'O1': 1.2,
 'O2': 1.8,
 'O3': 1.6,
 'O4': 1.4,
 'O5': 0.5,
 'O6': 1.1,
 '1O': 1.2,
 '11': 0.0,
 '12': 1.5,
 '13': 0.8,
 '14': 0.5,
 '15': 1.3,
 '16': 1.7,
 '2O': 1.8,
 '21': 1.5,
 '22': 0.0,
 '23': 2.1,
 '24': 1.9,
 '25': 1.1,
 '26': 0.6,
 '3O': 1.6,
 '31': 0.8,
 '32': 2.1,
 '33': 0.0,
 '34': 0.2,
 '35': 0.7,
 '36': 1.8,
 '4O': 1.4,
 '41': 0.5,
 '42': 1.9,
 '43': 0.1,
 '44': 0.0,
 '45': 1.1,
 '46': 1.7,
 '5O': 0.5,
 '51': 1.3,
 '52': 1.1,
 '53': 0.7,
 '54': 1.1,
 '55': 0.0,
 '56': 0.3,
 '6O': 1.1,
 '61': 1.7,
 '62': 0.6,
 '63': 2.0,
 '64': 1.7,
 '65': 0.3,
 '66': 0.0}

In [317]:
# constraints time 2 for j in() xijk*e_i <= s_ik  (xi1k_+xi2k+...+xink)*l_i <= sik 
full_names = my_names + time_names
constraints_time_2 = []
_i=0
for i in (["O"] + customers[:num_customers]):
    for k in vehicles[:num_vehicles]:
        _i+=1
        constraints_time_2.append(([(-1 if name[1] == i and name[2] == k else 0) if name[0] == "s" \
                                    else start_time[i] if (name[0] == "x" and name[1] == i and name[3] == k) else 0 for name in full_names], "L", 0 , "CT2" +str(_i)))
displayful(constraints_time_2)

CT21: ([-sO1]  L  0)
CT22: ([-sO2]  L  0)
CT23: ([-sO3]  L  0)
CT24: ([-sO4]  L  0)
CT25: ([-sO5]  L  0)
CT26: ([2.0x111 2.0x121 2.0x131 2.0x141 2.0x151 2.0x161 2.0x1X1 -s11]  L  0)
CT27: ([2.0x112 2.0x122 2.0x132 2.0x142 2.0x152 2.0x162 2.0x1X2 -s12]  L  0)
CT28: ([2.0x113 2.0x123 2.0x133 2.0x143 2.0x153 2.0x163 2.0x1X3 -s13]  L  0)
CT29: ([2.0x114 2.0x124 2.0x134 2.0x144 2.0x154 2.0x164 2.0x1X4 -s14]  L  0)
CT210: ([2.0x115 2.0x125 2.0x135 2.0x145 2.0x155 2.0x165 2.0x1X5 -s15]  L  0)
CT211: ([-s21]  L  0)
CT212: ([-s22]  L  0)
CT213: ([-s23]  L  0)
CT214: ([-s24]  L  0)
CT215: ([-s25]  L  0)
CT216: ([3.5x311 3.5x321 3.5x331 3.5x341 3.5x351 3.5x361 3.5x3X1 -s31]  L  0)
CT217: ([3.5x312 3.5x322 3.5x332 3.5x342 3.5x352 3.5x362 3.5x3X2 -s32]  L  0)
CT218: ([3.5x313 3.5x323 3.5x333 3.5x343 3.5x353 3.5x363 3.5x3X3 -s33]  L  0)
CT219: ([3.5x314 3.5x324 3.5x334 3.5x344 3.5x354 3.5x364 3.5x3X4 -s34]  L  0)
CT220: ([3.5x315 3.5x325 3.5x335 3.5x345 3.5x355 3.5x365 3.5x3X5 -s35]  L  0)
CT221: ([

In [318]:
# constraints_time_3 s_ik <= l_i*sum(xijk)
constraints_time_3 = []
_i=0

for i in (["O"] + customers[:num_customers]):
    for k in vehicles[:num_vehicles]:
        _i+=1
        constraints_time_3.append(([(-1 if name[1] == i and name[2] == k else 0) if name[0] == "s" \
                                    else end_time[i] if (name[0] == "x" and name[1] == i and name[3] == k) else 0 for name in full_names], "G", 0 , "CT3" +str(_i)))
displayful(constraints_time_3)


CT31: ([5.0xO11 5.0xO21 5.0xO31 5.0xO41 5.0xO51 5.0xO61 5.0xOX1 -sO1]  G  0)
CT32: ([5.0xO12 5.0xO22 5.0xO32 5.0xO42 5.0xO52 5.0xO62 5.0xOX2 -sO2]  G  0)
CT33: ([5.0xO13 5.0xO23 5.0xO33 5.0xO43 5.0xO53 5.0xO63 5.0xOX3 -sO3]  G  0)
CT34: ([5.0xO14 5.0xO24 5.0xO34 5.0xO44 5.0xO54 5.0xO64 5.0xOX4 -sO4]  G  0)
CT35: ([5.0xO15 5.0xO25 5.0xO35 5.0xO45 5.0xO55 5.0xO65 5.0xOX5 -sO5]  G  0)
CT36: ([13.0x111 13.0x121 13.0x131 13.0x141 13.0x151 13.0x161 13.0x1X1 -s11]  G  0)
CT37: ([13.0x112 13.0x122 13.0x132 13.0x142 13.0x152 13.0x162 13.0x1X2 -s12]  G  0)
CT38: ([13.0x113 13.0x123 13.0x133 13.0x143 13.0x153 13.0x163 13.0x1X3 -s13]  G  0)
CT39: ([13.0x114 13.0x124 13.0x134 13.0x144 13.0x154 13.0x164 13.0x1X4 -s14]  G  0)
CT310: ([13.0x115 13.0x125 13.0x135 13.0x145 13.0x155 13.0x165 13.0x1X5 -s15]  G  0)
CT311: ([15.0x211 15.0x221 15.0x231 15.0x241 15.0x251 15.0x261 15.0x2X1 -s21]  G  0)
CT312: ([15.0x212 15.0x222 15.0x232 15.0x242 15.0x252 15.0x262 15.0x2X2 -s22]  G  0)
CT313: ([15.0x213 15.0x2

In [319]:
# constraints time 4
constraints_time_4 = []
_i=0
    
for k in vehicles[:num_vehicles]:
    for i in ["O"] + customers[:num_customers]:
        for j in customers[:num_customers] + ["X"]:
            if i==j:
                continue
#             
#             constraints_time_4.append((obj, "L", 0 , "CT4" +str(_i)))
            
            _m = max(end_time[i] + times[i+("O" if j == "X" else j)] - start_time[i], 0)
            
            obj = [(1 if name[1] == i else -1 if name[1] == j else 0) if (name[0] == "s" and name[2] == k) \
                   else _m if (name[0] == "x" and name[1] == i and name[2] == j and name[3] == k) else 0 \
                   for name in full_names if i != j]
        
            rhs = _m - times[i+("O" if j == "X" else j)]
            
            if len([o for o in obj if o != 0]) > 0:
                _i+=1
                constraints_time_4.append((obj, "L", rhs , "CT3" +str(_i)))
                
                
displayful(constraints_time_4)



CT31: ([6.2xO11 sO1 -s11]  L  5.0)
CT32: ([6.8xO21 sO1 -s21]  L  5.0)
CT33: ([6.6xO31 sO1 -s31]  L  5.0)
CT34: ([6.4xO41 sO1 -s41]  L  5.0)
CT35: ([5.5xO51 sO1 -s51]  L  5.0)
CT36: ([6.1xO61 sO1 -s61]  L  5.0)
CT37: ([5.0xOX1 sO1 -sX1]  L  5.0)
CT38: ([12.5x121 s11 -s21]  L  11.0)
CT39: ([11.8x131 s11 -s31]  L  11.0)
CT310: ([11.5x141 s11 -s41]  L  11.0)
CT311: ([12.3x151 s11 -s51]  L  11.0)
CT312: ([12.7x161 s11 -s61]  L  11.0)
CT313: ([12.2x1X1 s11 -sX1]  L  11.0)
CT314: ([16.5x211 -s11 s21]  L  15.0)
CT315: ([17.1x231 s21 -s31]  L  15.0)
CT316: ([16.9x241 s21 -s41]  L  15.0)
CT317: ([16.1x251 s21 -s51]  L  15.0)
CT318: ([15.6x261 s21 -s61]  L  15.0)
CT319: ([16.8x2X1 s21 -sX1]  L  15.0)
CT320: ([14.3x311 -s11 s31]  L  13.5)
CT321: ([15.6x321 -s21 s31]  L  13.5)
CT322: ([13.7x341 s31 -s41]  L  13.5)
CT323: ([14.2x351 s31 -s51]  L  13.5)
CT324: ([15.3x361 s31 -s61]  L  13.5)
CT325: ([15.1x3X1 s31 -sX1]  L  13.5)
CT326: ([12.0x411 -s11 s41]  L  11.5)
CT327: ([13.4x421 -s21 s41]  L  11.

In [320]:
# Merge segment constraints
constraints_group = []
constraints_group += constraint_2 
constraints_group += constraint_3 
constraints_group += constraint_4 
constraints_group += constraint_5 
constraints_group += constraint_6
constraints_group += constraint_x
constraints_group += constraint_y
constraints_group += constraint_z
# constraints_group += constraints_time_1
constraints_group += constraints_time_2
constraints_group += constraints_time_3
constraints_group += constraints_time_4


# Convert for cplex
constraints_ = []
constraint_senses = []
rhs = []
constraint_names = []
for i in constraints_group:
    constraints_.append([full_names if i[3][:2] == "CT" else my_names, i[0]])
    constraint_senses.append(i[1])
    rhs.append(i[2])
    constraint_names.append(i[3])
    
print(constraints_)
# print(constraint_senses)
# print(rhs)

[[['xO11', 'xO21', 'xO31', 'xO41', 'xO51', 'xO61', 'xOX1', 'x111', 'x121', 'x131', 'x141', 'x151', 'x161', 'x1X1', 'x211', 'x221', 'x231', 'x241', 'x251', 'x261', 'x2X1', 'x311', 'x321', 'x331', 'x341', 'x351', 'x361', 'x3X1', 'x411', 'x421', 'x431', 'x441', 'x451', 'x461', 'x4X1', 'x511', 'x521', 'x531', 'x541', 'x551', 'x561', 'x5X1', 'x611', 'x621', 'x631', 'x641', 'x651', 'x661', 'x6X1', 'xO12', 'xO22', 'xO32', 'xO42', 'xO52', 'xO62', 'xOX2', 'x112', 'x122', 'x132', 'x142', 'x152', 'x162', 'x1X2', 'x212', 'x222', 'x232', 'x242', 'x252', 'x262', 'x2X2', 'x312', 'x322', 'x332', 'x342', 'x352', 'x362', 'x3X2', 'x412', 'x422', 'x432', 'x442', 'x452', 'x462', 'x4X2', 'x512', 'x522', 'x532', 'x542', 'x552', 'x562', 'x5X2', 'x612', 'x622', 'x632', 'x642', 'x652', 'x662', 'x6X2', 'xO13', 'xO23', 'xO33', 'xO43', 'xO53', 'xO63', 'xOX3', 'x113', 'x123', 'x133', 'x143', 'x153', 'x163', 'x1X3', 'x213', 'x223', 'x233', 'x243', 'x253', 'x263', 'x2X3', 'x313', 'x323', 'x333', 'x343', 'x353', 'x363

In [321]:
# Create Cplex Problems

myProblem = None

try:
    myProblem = cplex.Cplex()     
except CplexError:
    print ("exc")
print(len(my_obj), len(my_names))
myProblem.variables.add(obj = my_obj,
                      lb = lower_bounds,
                      ub = upper_bounds,
                      names = my_names)

myProblem.variables.add(names= time_names , types = ["C"]*len(time_names),ub = [cplex.infinity]*len(time_names)) 


myProblem.objective.set_sense(myProblem.objective.sense.minimize)

for i in range(0, num_names):
    myProblem.variables.set_types(i,myProblem.variables.type.binary)

myProblem.linear_constraints.add(lin_expr = constraints_,
                                 senses = constraint_senses,
                                 rhs = rhs,
                                 names = constraint_names)

print(myProblem.variables.get_names())
print(myProblem.variables.get_types())
print(myProblem.variables.get_upper_bounds())
print(myProblem.variables.get_lower_bounds())


245 245
['xO11', 'xO21', 'xO31', 'xO41', 'xO51', 'xO61', 'xOX1', 'x111', 'x121', 'x131', 'x141', 'x151', 'x161', 'x1X1', 'x211', 'x221', 'x231', 'x241', 'x251', 'x261', 'x2X1', 'x311', 'x321', 'x331', 'x341', 'x351', 'x361', 'x3X1', 'x411', 'x421', 'x431', 'x441', 'x451', 'x461', 'x4X1', 'x511', 'x521', 'x531', 'x541', 'x551', 'x561', 'x5X1', 'x611', 'x621', 'x631', 'x641', 'x651', 'x661', 'x6X1', 'xO12', 'xO22', 'xO32', 'xO42', 'xO52', 'xO62', 'xOX2', 'x112', 'x122', 'x132', 'x142', 'x152', 'x162', 'x1X2', 'x212', 'x222', 'x232', 'x242', 'x252', 'x262', 'x2X2', 'x312', 'x322', 'x332', 'x342', 'x352', 'x362', 'x3X2', 'x412', 'x422', 'x432', 'x442', 'x452', 'x462', 'x4X2', 'x512', 'x522', 'x532', 'x542', 'x552', 'x562', 'x5X2', 'x612', 'x622', 'x632', 'x642', 'x652', 'x662', 'x6X2', 'xO13', 'xO23', 'xO33', 'xO43', 'xO53', 'xO63', 'xOX3', 'x113', 'x123', 'x133', 'x143', 'x153', 'x163', 'x1X3', 'x213', 'x223', 'x233', 'x243', 'x253', 'x263', 'x2X3', 'x313', 'x323', 'x333', 'x343', 'x353',

In [322]:
# Find the solutions
try:
    myProblem.solve()
    
    print(myProblem.get_stats())
    values=myProblem.solution.get_values()
    names=myProblem.variables.get_names()
    
    for v, n in zip(values, names):
        if v != 0:
            print(n, " - ",v)
except cplex.exceptions.errors.CplexSolverError:
    print("No solution")
    


Version identifier: 20.1.0.0 | 2020-11-11 | 9bedb6d68
CPXPARAM_Read_DataCheck                          1
Tried aggregator 1 time.
MIP Presolve eliminated 81 rows and 40 columns.
MIP Presolve modified 308 coefficients.
Reduced MIP has 328 rows, 245 columns, and 3985 nonzeros.
Reduced MIP has 215 binaries, 0 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.00 sec. (5.21 ticks)
Found incumbent of value 222.000000 after 0.00 sec. (7.77 ticks)
Probing time = 0.02 sec. (2.98 ticks)
Tried aggregator 1 time.
Detecting symmetries...
Reduced MIP has 328 rows, 245 columns, and 3985 nonzeros.
Reduced MIP has 215 binaries, 0 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.00 sec. (2.37 ticks)
Probing time = 0.00 sec. (2.96 ticks)
Clique table members: 2122.
MIP emphasis: balance optimality and feasibility.
MIP search method: dynamic search.
Parallel mode: deterministic, using up to 8 threads.
Root relaxation solution time = 0.00 sec. (1.29 ticks)

        Nodes                           